### PR TITLE
Feature/api objects

### PR DESCRIPTION
**Pull request by lottspot**
Pull request for: #4 #5 #6 #7 #8
# Development checklist (To be completed by main developer)
- [x] Code is working as expected
- [x] Acceptance criteria met
- [ ] Passes coding standards
- [ ] Unit tests written and passing
- [x] PR open and linked to issue
- [x] PR using correct template
- [ ] Issue closed
- [x] A quick self code review performed
# Code Review Checklist
## Code
- No syntax/runtime errors and warnings in the code
- No deprecated functions in the code
- “Dead Code” should be removed. If it is a temporary hack, it should be identified as such.
- All code follows coding standard (preferably https://github.com/airbnb/javascript)
- No magic numbers. There should be no magic numbers like 6,10 etc… any numbers like this should be defined as a constant. And Constants should be well commented about the purpose.
- [x] Above criteria met
## Documentation
- All methods are commented in clear language. If it is unclear to the reader, it is unclear to the user.
- All class, variable, and method modifiers should be examined for correctness.
- Describe behaviour for known input corner-cases.
- Complex algorithms should be explained with references. For example,  document the reference that identifies the equation, formula, or pattern. In all cases, examine the algorithm and determine if it can be simplified.
- Incomplete code is marked with `//TODO` or `//FIXME` markers.
- All public and private APIs are examined for updates.
- [ ] Above criteria met
## Unit Tests
- Unit tests are added for each code path, and behaviour.
- Unit tests must cover error conditions and invalid parameter cases.
- Unit tests for standard algorithms should be examined against the standard for expected results.
- Ensure that the code fixes the issue, or implements the requirement, and that the unit test confirms it. If the unit test confirms a fix for issue, add the issue number to the doc block.
- Unit tests must have assertions
- Regression tests for fixes are included.
- As a reviewer, you should understand the code. If you don’t, the review may not be complete, or the code may not be well commented.
- [ ] Above criteria met
## Error Handling
- Invalid parameter values are handled properly early in methods (Fast Fail/Return Early).
- **Don't swallow exceptions!** You should at least log the exception.
- [x] Above criteria met
# Testing checklist
- [ ] All unit tests pass
- [ ] All acceptance criteria are met and working as expected
- [ ] Spot checks have been performed on existing functionality that may have been affected

### CODE REVIEW

**Comment by lottspot** [comment]
Because I added a commit to the work done by @kgdiem, I think it would be appropriate to have @BayoAdejare or @modpluz perform the review here rather than me

**Review by modpluz — COMMENTED** [review]
lgtm overall. Just one (perhaps, preferential) question. Are we frowning against using anonymous functions? :)

**Comment by lottspot** [comment]
Personally, my preference would also be to use anonymous functions when assigning object methods to a prototype, but since it's really a cosmetic/preferential thing, we ought to yield to the preference of the author. Or as we like to say around the office.... "first past the post" gets to decide ;)

**Comment by lottspot** [comment]
and in this case, first past the post is @kgdiem

**Comment by modpluz** [comment]
@jlott, yeah perhaps one of the few things I don't like about the airbnb standards.

**Comment by lottspot** [comment]
Thanks for jamming this out for us @kgdiem!

**Comment by kgdiem** [comment]
NP. I like to use named functions (almost) always so that the stack trace is more expressive. 

Also, would y'all consider this one of the cases we discussed where unit tests aren't required? I can see a point for and against them in this scenario.

**Pull request merged**
